steps:
  # Step 1: Pull Docker image from Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'us-central1-docker.pkg.dev/my-project-57732-v/three-tier/frontend']

  - name: 'hashicorp/terraform:light'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        cd Terraform &&
        terraform init -input=false &&
        terraform plan -input=false

options:
  logging: CLOUD_LOGGING_ONLY