steps:
- name: 'gcr.io/cloudbuild-templates/terraform-init'
  entrypoint: 'terraform'
  args: ['init']
- name: 'gcr.io/cloudbuild-templates/terraform-fmt'
  entrypoint: 'terraform'
  args: ['fmt']
- name: 'gcr.io/cloudbuild-templates/terraform-plan'
  entrypoint: 'terraform'
  args: ['plan']
- name: 'gcr.io/cloudbuild-templates/terraform-apply'
  entrypoint: 'terraform'
  args: ['apply', '-auto-approve']
- name: 'gcr.io/cloudbuilders/docker'
  args: ['-t', 'us-docker.pkg.dev/your-project-id/your-repo/your-image:latest', '.']
- name: 'gcr.io/cloudbuilders/gcloud'
  args: ['compute', 'ssh', 'my-vm', '--zone', 'us-central1-a', '--command', 'docker', 'run', '-d', '-p', '8080:80', 'us-docker.pkg.dev/your-project-id/your-repo/your-image:latest']
options:
  logging: CLOUD_LOGGING_ONLY

