steps:
  # Step 3: Set up Terraform environment and run terraform plan
  - name: 'hashicorp/terraform:light'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        ls &&
        cd Terraform &&
        ls &&
        terraform init -input=false &&
        terraform plan -input=false 


  - name: hashicorp/terraform:light
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        ls &&
        terraform apply -input=false -auto-approve 
         
options:
  logging: CLOUD_LOGGING_ONLY
