# Use the official Python image with Python 3.11
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Flask and Werkzeug
RUN pip install -r requirements.txt

# Copy the rest of your application code into the container
COPY . .

# Command to run your Flask application
CMD ["flask", "run", "--host=0.0.0.0"]

